### ISSUE TITLE
Some default backgrounds regressed

### ISSUE THREAD

**Issue by lukeblevins** [jimmac/silverblue-wallpapers#1]
Commit 5d84446228d1b627c595a877e93819580860e447 appears to have broken the loading of the stunning Default-Night.jpg wallpaper.

![Screenshot from 2020-05-08 18-12-43](https://user-images.githubusercontent.com/20365014/81453743-65d79c00-9158-11ea-8b43-94cf3825db6d.png)

I really like this set of wallpapers and wish to use them on my Silverblue machine soon.

**Comment by jimmac** [comment]
That was an intentional change, but perhaps the night variant lost a tad more detail.
